### ISSUE TITLE
Legendary Hoe Shape

### ISSUE THREAD

**Issue by funnybunnyofdoom** [funnybunnyofdoom/Vintage-Story-Mods#10]

**Comment by Kialiathesweeper89** [comment]
[legendaryhoe.zip](https://github.com/funnybunnyofdoom/Vintage-Story-Mods/files/9924922/legendaryhoe.zip)

**Comment by Kialiathesweeper89** [comment]
![Image](https://user-images.githubusercontent.com/109701371/199628607-216692da-20ed-4e27-8c3d-1487d0634fe1.png)



![Image](https://user-images.githubusercontent.com/109701371/199628615-eac62935-e031-4b59-9887-f0f78d191553.png)



![Image](https://user-images.githubusercontent.com/109701371/199628626-ad673271-66a6-4072-9194-1ab4cfa98ba6.png)


[legendaryhoeparts.zip](https://github.com/funnybunnyofdoom/Vintage-Story-Mods/files/9924994/legendaryhoeparts.zip)
