### ISSUE TITLE
It seems tpt accept is broken, people are getting "an exception was thrown while executing command: the given key was not present in the dictionary"

### ISSUE THREAD

**Issue by WickedSchnitzel** [funnybunnyofdoom/Vintage-Story-Mods#183]
Please look into it. And if possible, let us disable /sethome (while /home can be active - teleporting to spawns set with a temp gear only)

**Comment by funnybunnyofdoom** [comment]
Going to look into both of these things. I am really busy right now, but I want you to know that I will make sure to get this fixed, and the separate /sethome and /home commands.

**Comment by funnybunnyofdoom** [comment]
This should now be resolved with some extra error checking. /tpt wipe will also allow the tpt dictionaries to be wiped if this issue occurs again. Please let me know if the next release doesn't solve this.
