### ISSUE TITLE
Hoe Parts Shape

### ISSUE THREAD

**Issue by funnybunnyofdoom** [funnybunnyofdoom/Vintage-Story-Mods#24]

**Comment by Kialiathesweeper89** [comment]
![Image](https://user-images.githubusercontent.com/109701371/199629171-9d7dd824-ee97-4134-8adf-dfb32bd37462.png)



![Image](https://user-images.githubusercontent.com/109701371/199629177-a9557bb7-e425-4683-b359-c9e492fdee2a.png)



![Image](https://user-images.githubusercontent.com/109701371/199629187-d7eacabf-cfe5-4d9a-b7f0-284af900bb21.png)



[legendaryhoeparts.zip](https://github.com/funnybunnyofdoom/Vintage-Story-Mods/files/9925020/legendaryhoeparts.zip)
