### ISSUE TITLE
Ladders can not be placed on the sides of dirt roads

### ISSUE THREAD

**Issue by Kialiathesweeper89** [funnybunnyofdoom/Vintage-Story-Mods#429]
If you make a dirt road around a pit trap, you are unable to place a ladder on the exposed side of the dirt road to climb out of your pit. Seems to only be dirt roads at the moment, the wooden plank roads you can place ladders on the sides of the block. When trying to place a ladder on the side of Dirt Road it gives the error message "cannot place a ladder here, no spot to attach to" which is the same message as a plowed crop block instead of a regular road block. See attached pictures.

![image](https://github.com/user-attachments/assets/9fa4a770-05f4-4a26-9ad7-e8406fc706a4)
![image](https://github.com/user-attachments/assets/0d9660eb-281c-4755-bcfd-cdd7e5904c63)
![image](https://github.com/user-attachments/assets/d481e59c-bbec-4e53-b20f-5a40c6556b2a)
![image](https://github.com/user-attachments/assets/89951953-d302-4418-8a2f-bc2792f57c66)

**Comment by funnybunnyofdoom** [comment]
Looks like the ladder just needs an attach point below it. You can't place ladders without a ladder or solid block beneath them on the roads.
